version: '3'
services:
  mongo:
    image: mongo
    restart: always
    networks:
      - dbnet
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - dbnet
    ports:
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://root:example@mongo:27017?directConnection=true&serverSelectionTimeoutMS=2000

networks:
  dbnet:
    driver: bridge
